export const stocks = [
  {
    stockSymbol: "AAPL",
    stockName: "Apple Inc.",
    avgTradePrice: 175.25,
    prevClose: 168.94,
  },
  {
    stockSymbol: "MSFT",
    stockName: "Microsoft Corporation",
    avgTradePrice: 342.15,
    prevClose: 330.47,
  },
  {
    stockSymbol: "GOOGL",
    stockName: "Alphabet Inc.",
    avgTradePrice: 132.45,
    prevClose: 130.32,
  },
  {
    stockSymbol: "AMZN",
    stockName: "Amazon.com Inc.",
    avgTradePrice: 145.3,
    prevClose: 147.72,
  },
  {
    stockSymbol: "TSLA",
    stockName: "Tesla Inc.",
    avgTradePrice: 250.5,
    prevClose: 244.97,
  },
  {
    stockSymbol: "FB",
    stockName: "Meta Platforms Inc.",
    avgTradePrice: 300.2,
    prevClose: 290.69,
  },
  {
    stockSymbol: "NFLX",
    stockName: "Netflix Inc.",
    avgTradePrice: 450.1,
    prevClose: 460.76,
  },
  {
    stockSymbol: "NVDA",
    stockName: "NVIDIA Corporation",
    avgTradePrice: 475,
    prevClose: 460.07,
  },
  {
    stockSymbol: "BRK.B",
    stockName: "Berkshire Hathaway Inc.",
    avgTradePrice: 350.75,
    prevClose: 359.32,
  },
  {
    stockSymbol: "JPM",
    stockName: "JPMorgan Chase & Co.",
    avgTradePrice: 140.25,
    prevClose: 142.31,
  },
  {
    stockSymbol: "V",
    stockName: "Visa Inc.",
    avgTradePrice: 230.15,
    prevClose: 237.55,
  },
  {
    stockSymbol: "MA",
    stockName: "Mastercard Incorporated",
    avgTradePrice: 390.5,
    prevClose: 396.03,
  },
  {
    stockSymbol: "DIS",
    stockName: "The Walt Disney Company",
    avgTradePrice: 120,
    prevClose: 115.64,
  },
  {
    stockSymbol: "PYPL",
    stockName: "PayPal Holdings Inc.",
    avgTradePrice: 75.2,
    prevClose: 77.26,
  },
  {
    stockSymbol: "ADBE",
    stockName: "Adobe Inc.",
    avgTradePrice: 560.3,
    prevClose: 553.08,
  },
  {
    stockSymbol: "CMCSA",
    stockName: "Comcast Corporation",
    avgTradePrice: 42.5,
    prevClose: 41.15,
  },
  {
    stockSymbol: "INTC",
    stockName: "Intel Corporation",
    avgTradePrice: 30.75,
    prevClose: 31.66,
  },
  {
    stockSymbol: "CSCO",
    stockName: "Cisco Systems Inc.",
    avgTradePrice: 52.1,
    prevClose: 50.93,
  },
  {
    stockSymbol: "PEP",
    stockName: "PepsiCo Inc.",
    avgTradePrice: 180,
    prevClose: 175.09,
  },
  {
    stockSymbol: "KO",
    stockName: "Coca-Cola Company",
    avgTradePrice: 60.25,
    prevClose: 59.54,
  },
  {
    stockSymbol: "PFE",
    stockName: "Pfizer Inc.",
    avgTradePrice: 45,
    prevClose: 43.28,
  },
  {
    stockSymbol: "MRK",
    stockName: "Merck & Co., Inc.",
    avgTradePrice: 90.5,
    prevClose: 93.42,
  },
  {
    stockSymbol: "ABT",
    stockName: "Abbott Laboratories",
    avgTradePrice: 110.2,
    prevClose: 114.31,
  },
  {
    stockSymbol: "NKE",
    stockName: "Nike Inc.",
    avgTradePrice: 120,
    prevClose: 116.82,
  },
  {
    stockSymbol: "T",
    stockName: "AT&T Inc.",
    avgTradePrice: 15.75,
    prevClose: 16.33,
  },
  {
    stockSymbol: "VZ",
    stockName: "Verizon Communications Inc.",
    avgTradePrice: 38.5,
    prevClose: 39.39,
  },
  {
    stockSymbol: "XOM",
    stockName: "Exxon Mobil Corporation",
    avgTradePrice: 105,
    prevClose: 101.61,
  },
  {
    stockSymbol: "CVX",
    stockName: "Chevron Corporation",
    avgTradePrice: 170.25,
    prevClose: 165.59,
  },
  {
    stockSymbol: "WMT",
    stockName: "Walmart Inc.",
    avgTradePrice: 160,
    prevClose: 165.14,
  },
  {
    stockSymbol: "HD",
    stockName: "The Home Depot, Inc.",
    avgTradePrice: 320.5,
    prevClose: 315.65,
  },
  {
    stockSymbol: "UNH",
    stockName: "UnitedHealth Group Incorporated",
    avgTradePrice: 490,
    prevClose: 482.27,
  },
  {
    stockSymbol: "JNJ",
    stockName: "Johnson & Johnson",
    avgTradePrice: 155.75,
    prevClose: 153.02,
  },
  {
    stockSymbol: "TMO",
    stockName: "Thermo Fisher Scientific Inc.",
    avgTradePrice: 600,
    prevClose: 589.7,
  },
  {
    stockSymbol: "LLY",
    stockName: "Eli Lilly and Company",
    avgTradePrice: 450.5,
    prevClose: 464.61,
  },
  {
    stockSymbol: "MDT",
    stockName: "Medtronic plc",
    avgTradePrice: 90,
    prevClose: 88.23,
  },
  {
    stockSymbol: "IBM",
    stockName: "International Business Machines Corporation",
    avgTradePrice: 140,
    prevClose: 141.68,
  },
  {
    stockSymbol: "TXN",
    stockName: "Texas Instruments Incorporated",
    avgTradePrice: 180,
    prevClose: 184.53,
  },
  {
    stockSymbol: "QCOM",
    stockName: "Qualcomm Incorporated",
    avgTradePrice: 120.75,
    prevClose: 124.99,
  },
  {
    stockSymbol: "NOW",
    stockName: "ServiceNow, Inc.",
    avgTradePrice: 550,
    prevClose: 533.89,
  },
  {
    stockSymbol: "CRM",
    stockName: "Salesforce, Inc.",
    avgTradePrice: 220,
    prevClose: 225.75,
  },
  {
    stockSymbol: "SNAP",
    stockName: "Snap Inc.",
    avgTradePrice: 10,
    prevClose: 9.73,
  },
  {
    stockSymbol: "ZM",
    stockName: "Zoom Video Communications, Inc.",
    avgTradePrice: 75,
    prevClose: 76.73,
  },
  {
    stockSymbol: "SPOT",
    stockName: "Spotify Technology S.A.",
    avgTradePrice: 150,
    prevClose: 144.49,
  },
  {
    stockSymbol: "PINS",
    stockName: "Pinterest, Inc.",
    avgTradePrice: 25,
    prevClose: 25.43,
  },
  {
    stockSymbol: "SQ",
    stockName: "Block, Inc.",
    avgTradePrice: 70,
    prevClose: 67.75,
  },
  {
    stockSymbol: "TWTR",
    stockName: "Twitter, Inc.",
    avgTradePrice: 45,
    prevClose: 44.18,
  },
  {
    stockSymbol: "BABA",
    stockName: "Alibaba Group Holding Limited",
    avgTradePrice: 85,
    prevClose: 82.41,
  },
  {
    stockSymbol: "JD",
    stockName: "JD.com, Inc.",
    avgTradePrice: 30,
    prevClose: 29,
  },
  {
    stockSymbol: "NIO",
    stockName: "NIO Inc.",
    avgTradePrice: 15,
    prevClose: 15.24,
  },
  {
    stockSymbol: "LI",
    stockName: "Li Auto Inc.",
    avgTradePrice: 25,
    prevClose: 24.33,
  },
  {
    stockSymbol: "XPEV",
    stockName: "XPeng Inc.",
    avgTradePrice: 20,
    prevClose: 20.64,
  },
  {
    stockSymbol: "F",
    stockName: "Ford Motor Company",
    avgTradePrice: 12,
    prevClose: 12.32,
  },
  {
    stockSymbol: "GM",
    stockName: "General Motors Company",
    avgTradePrice: 35,
    prevClose: 34.36,
  },
  {
    stockSymbol: "TSM",
    stockName: "Taiwan Semiconductor Manufacturing Company",
    avgTradePrice: 90,
    prevClose: 93.56,
  },
  {
    stockSymbol: "AVGO",
    stockName: "Broadcom Inc.",
    avgTradePrice: 850,
    prevClose: 876.81,
  },
  {
    stockSymbol: "AMD",
    stockName: "Advanced Micro Devices, Inc.",
    avgTradePrice: 105,
    prevClose: 103.18,
  },
  {
    stockSymbol: "INTU",
    stockName: "Intuit Inc.",
    avgTradePrice: 500,
    prevClose: 515.73,
  },
  {
    stockSymbol: "ATVI",
    stockName: "Activision Blizzard, Inc.",
    avgTradePrice: 75,
    prevClose: 75.96,
  },
  {
    stockSymbol: "EA",
    stockName: "Electronic Arts Inc.",
    avgTradePrice: 130,
    prevClose: 128.07,
  },
  {
    stockSymbol: "LRCX",
    stockName: "Lam Research Corporation",
    avgTradePrice: 570,
    prevClose: 589.62,
  },
  {
    stockSymbol: "AMAT",
    stockName: "Applied Materials, Inc.",
    avgTradePrice: 120,
    prevClose: 117.95,
  },
  {
    stockSymbol: "ADI",
    stockName: "Analog Devices, Inc.",
    avgTradePrice: 190,
    prevClose: 195.95,
  },
  {
    stockSymbol: "MCHP",
    stockName: "Microchip Technology Incorporated",
    avgTradePrice: 90,
    prevClose: 93.11,
  },
  {
    stockSymbol: "NXPI",
    stockName: "NXP Semiconductors N.V.",
    avgTradePrice: 190,
    prevClose: 196,
  },
  {
    stockSymbol: "BIDU",
    stockName: "Baidu, Inc.",
    avgTradePrice: 140,
    prevClose: 134.49,
  },
  {
    stockSymbol: "PDD",
    stockName: "Pinduoduo Inc.",
    avgTradePrice: 90,
    prevClose: 92.37,
  },
  {
    stockSymbol: "TCEHY",
    stockName: "Tencent Holdings Limited",
    avgTradePrice: 50,
    prevClose: 51.43,
  },
  {
    stockSymbol: "NTES",
    stockName: "NetEase, Inc.",
    avgTradePrice: 80,
    prevClose: 78.65,
  },
  {
    stockSymbol: "BILI",
    stockName: "Bilibili Inc.",
    avgTradePrice: 20,
    prevClose: 20.2,
  },
  {
    stockSymbol: "ICLK",
    stockName: "iClick Interactive Asia Group Limited",
    avgTradePrice: 15,
    prevClose: 14.72,
  },
  {
    stockSymbol: "BHP",
    stockName: "BHP Group",
    avgTradePrice: 60,
    prevClose: 58.66,
  },
  {
    stockSymbol: "RIO",
    stockName: "Rio Tinto Group",
    avgTradePrice: 70,
    prevClose: 67.48,
  },
  {
    stockSymbol: "VALE",
    stockName: "Vale S.A.",
    avgTradePrice: 15,
    prevClose: 15.55,
  },
  {
    stockSymbol: "NEM",
    stockName: "Newmont Corporation",
    avgTradePrice: 45,
    prevClose: 46.79,
  },
  {
    stockSymbol: "GOLD",
    stockName: "Barrick Gold Corporation",
    avgTradePrice: 18,
    prevClose: 17.56,
  },
  {
    stockSymbol: "SLV",
    stockName: "iShares Silver Trust",
    avgTradePrice: 23,
    prevClose: 23.61,
  },
  {
    stockSymbol: "SPY",
    stockName: "SPDR S&P 500 ETF Trust",
    avgTradePrice: 440,
    prevClose: 435.52,
  },
  {
    stockSymbol: "QQQ",
    stockName: "Invesco QQQ Trust",
    avgTradePrice: 370,
    prevClose: 381.41,
  },
  {
    stockSymbol: "IWM",
    stockName: "iShares Russell 2000 ETF",
    avgTradePrice: 200,
    prevClose: 196.68,
  },
  {
    stockSymbol: "DIA",
    stockName: "SPDR Dow Jones Industrial Average ETF Trust",
    avgTradePrice: 340,
    prevClose: 336.23,
  },
  {
    stockSymbol: "XLF",
    stockName: "Financial Select Sector SPDR Fund",
    avgTradePrice: 36,
    prevClose: 35.47,
  },
  {
    stockSymbol: "XLY",
    stockName: "Consumer Discretionary Select Sector SPDR Fund",
    avgTradePrice: 185,
    prevClose: 178.83,
  },
  {
    stockSymbol: "XLC",
    stockName: "Communication Services Select Sector SPDR Fund",
    avgTradePrice: 60,
    prevClose: 60.85,
  },
  {
    stockSymbol: "XLI",
    stockName: "Industrial Select Sector SPDR Fund",
    avgTradePrice: 105,
    prevClose: 103.07,
  },
  {
    stockSymbol: "XLB",
    stockName: "Materials Select Sector SPDR Fund",
    avgTradePrice: 85,
    prevClose: 86.89,
  },
  {
    stockSymbol: "HINDUNILVR",
    stockName: "Hindustan Unilever Ltd",
    avgTradePrice: 2933,
    prevClose: 2859.41,
  },
  {
    stockSymbol: "BHARTIARTL",
    stockName: "Bharti Airtel Ltd",
    avgTradePrice: 834.5,
    prevClose: 805.23,
  },
  {
    stockSymbol: "HDFCBANK",
    stockName: "HDFC Bank Ltd",
    avgTradePrice: 1568.5,
    prevClose: 1519.93,
  },
  {
    stockSymbol: "INFY",
    stockName: "Infosys Ltd",
    avgTradePrice: 1470,
    prevClose: 1489.51,
  },
  {
    stockSymbol: "KPITTECH",
    stockName: "KPIT Technologies Ltd",
    avgTradePrice: 800,
    prevClose: 817.12,
  },
  {
    stockSymbol: "M&M",
    stockName: "Mahindra & Mahindra Ltd",
    avgTradePrice: 1400,
    prevClose: 1362.13,
  },
  {
    stockSymbol: "RELIANCE",
    stockName: "Reliance Industries Ltd",
    avgTradePrice: 2500,
    prevClose: 2422.59,
  },
  {
    stockSymbol: "SBIN",
    stockName: "State Bank of India",
    avgTradePrice: 600,
    prevClose: 610.26,
  },
  {
    stockSymbol: "SGBMAY29",
    stockName: "Sovereign Gold Bond May 2029",
    avgTradePrice: 5500,
    prevClose: 5618.49,
  },
  {
    stockSymbol: "TATAPOWER",
    stockName: "Tata Power Company Ltd",
    avgTradePrice: 280,
    prevClose: 283.15,
  },
  {
    stockSymbol: "TCS",
    stockName: "Tata Consultancy Services Ltd",
    avgTradePrice: 3500,
    prevClose: 3411.88,
  },
  {
    stockSymbol: "WIPRO",
    stockName: "Wipro Ltd",
    avgTradePrice: 400,
    prevClose: 392.7,
  },
  {
    stockSymbol: "ITC",
    stockName: "ITC Ltd",
    avgTradePrice: 500,
    prevClose: 492.89,
  },
];
